# A better db model generated by AI
from django.db import models

class Product(models.Model):
    name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class ProductDescription(models.Model):
    product = models.OneToOneField(Product, on_delete=models.CASCADE, related_name='description')
    features = models.TextField()
    warranty = models.CharField(max_length=100, blank=True, null=True)
    additional_information = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"Description for {self.product.name}"
